name: conversion-report-service

services:
  report_postgres:
    image: postgres:16
    container_name: report-postgres
    environment:
      POSTGRES_USER: report_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: report_db
    ports:
      - "5436:5432"
    volumes:
      - report_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - conversion-report-network

  redis:
    image: redis:7
    container_name: report-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - conversion-report-network
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - conversion-report-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    depends_on:
      - zookeeper
    networks:
      - conversion-report-network
    volumes:
      - kafka_data:/var/lib/kafka/data
    ports:
      - "9093:9093"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - conversion-report-network
    ports:
      - "8005:8080"
    volumes:
      - ../Presentation/ConversionReportService.Presentation.Kafka/Protos:/schemas
    environment:
      kafka.clusters.0.name: kafka
      kafka.clusters.0.bootstrapServers: kafka:9092

      kafka.clusters.0.defaultKeySerde: ProtobufFile
      kafka.clusters.0.defaultValueSerde: ProtobufFile

      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.report_requested: ReportRequestedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.report_requested: ReportRequestedValue

networks:
  conversion-report-network:
    driver: bridge

volumes:
  report_pgdata: {}
  kafka_data: {}
  redis_data: {}
